"""
Cron配置管理服务
负责从数据库读取cron配置，生成crontab并安装到系统
"""
import logging
import subprocess
import os
from typing import List, Dict
from datetime import datetime

from app.db.session import SessionLocal
from app.models.cron_config import CronConfig

logger = logging.getLogger(__name__)


class CronManager:
    """Cron配置管理器"""
    
    def __init__(self):
        # 根据环境自动检测项目根路径
        self.project_root = os.getenv('PROJECT_ROOT', '/app')
        # 智能检测Python路径：优先使用虚拟环境，否则使用系统Python
        venv_python = os.path.join(self.project_root, 'venv', 'bin', 'python')
        if os.path.exists(venv_python):
            self.python_executable = venv_python
        else:
            # 容器内使用系统Python
            import sys
            self.python_executable = sys.executable
        self.scripts_dir = os.path.join(self.project_root, 'scripts', 'cron_jobs')
        self.logs_dir = os.path.join(self.project_root, 'logs')
        
    def load_cron_configs_from_db(self) -> List[CronConfig]:
        """从数据库读取启用的cron配置"""
        db = SessionLocal()
        try:
            configs = CronConfig.get_enabled_configs(db)
            logger.info(f"从数据库加载了 {len(configs)} 个启用的cron配置")
            return configs
        finally:
            db.close()
    
    def generate_crontab(self) -> str:
        """生成crontab内容"""
        configs = self.load_cron_configs_from_db()
        
        lines = [
            "# Auto-generated by DailyDigest - DO NOT EDIT MANUALLY\n",
            f"# Generated at: {datetime.now().isoformat()}\n",
            "# \n",
            "# Cron format: minute hour day month weekday command\n",
            "# Example: 0 */1 * * * means every hour at minute 0\n",
            "# \n",
            "\n"
        ]
        
        if not configs:
            lines.append("# No enabled cron jobs configured\n")
            logger.warning("没有启用的cron配置")
            return "".join(lines)
        
        for config in configs:
            if not config.enabled:
                continue
                
            script_path = os.path.join(self.scripts_dir, f"{config.task_name}_job.py")
            log_path = os.path.join(self.logs_dir, f"cron_{config.task_name}.log")
            
            # 确保脚本存在
            if not os.path.exists(script_path):
                logger.warning(f"脚本不存在: {script_path}，跳过")
                continue
            
            # 生成cron行
            lines.append(f"# {config.description or config.task_name}\n")
            lines.append(
                f"{config.cron_expression} cd {self.project_root} && "
                f"{self.python_executable} {script_path} >> {log_path} 2>&1\n"
            )
            lines.append("\n")
        
        content = "".join(lines)
        logger.info(f"生成crontab内容，共 {len(configs)} 个任务")
        logger.debug(f"Crontab内容:\n{content}")
        
        return content
    
    def install_crontab(self, content: str = None):
        """安装crontab到系统"""
        if content is None:
            content = self.generate_crontab()
        
        try:
            # 使用crontab命令安装
            process = subprocess.run(
                ['crontab', '-'],
                input=content.encode('utf-8'),
                capture_output=True,
                check=True
            )
            
            logger.info("Crontab已成功安装到系统")
            return True
            
        except subprocess.CalledProcessError as e:
            error_msg = f"安装crontab失败: {e.stderr.decode('utf-8')}"
            logger.error(error_msg)
            raise Exception(error_msg)
        except FileNotFoundError:
            error_msg = "crontab命令不存在，请确保系统已安装cron"
            logger.error(error_msg)
            raise Exception(error_msg)
        except Exception as e:
            error_msg = f"安装crontab时出现未知错误: {str(e)}"
            logger.error(error_msg)
            raise Exception(error_msg)
    
    def reload_crontab(self):
        """重新加载crontab（从数据库读取配置并安装）"""
        logger.info("开始重新加载crontab...")
        
        try:
            content = self.generate_crontab()
            self.install_crontab(content)
            logger.info("Crontab重新加载成功")
            return {
                'status': 'success',
                'message': 'Crontab已重新加载',
                'reload_time': datetime.now().isoformat()
            }
        except Exception as e:
            logger.error(f"重新加载crontab失败: {str(e)}")
            return {
                'status': 'error',
                'message': f'重新加载失败: {str(e)}'
            }
    
    def get_current_crontab(self) -> str:
        """获取当前系统的crontab内容"""
        try:
            process = subprocess.run(
                ['crontab', '-l'],
                capture_output=True,
                check=True
            )
            return process.stdout.decode('utf-8')
        except subprocess.CalledProcessError as e:
            if e.returncode == 1 and 'no crontab' in e.stderr.decode('utf-8').lower():
                return ""
            raise
        except Exception as e:
            logger.error(f"获取当前crontab失败: {str(e)}")
            return ""
    
    def verify_crontab(self) -> Dict:
        """验证crontab是否正确安装"""
        try:
            current = self.get_current_crontab()
            configs = self.load_cron_configs_from_db()
            
            # 检查每个配置是否在crontab中
            missing = []
            for config in configs:
                if config.enabled and config.task_name not in current:
                    missing.append(config.task_name)
            
            if missing:
                return {
                    'verified': False,
                    'message': f'以下任务未在crontab中找到: {", ".join(missing)}',
                    'missing_tasks': missing
                }
            
            return {
                'verified': True,
                'message': '所有启用的任务都已正确配置在crontab中',
                'task_count': len(configs)
            }
            
        except Exception as e:
            logger.error(f"验证crontab失败: {str(e)}")
            return {
                'verified': False,
                'message': f'验证失败: {str(e)}'
            }
    
    def get_all_configs(self) -> List[Dict]:
        """获取所有cron配置（包括禁用的）"""
        db = SessionLocal()
        try:
            configs = db.query(CronConfig).all()
            return [config.to_dict() for config in configs]
        finally:
            db.close()
    
    def update_config(self, config_id: int, cron_expression: str = None,
                     enabled: bool = None, description: str = None) -> Dict:
        """更新cron配置"""
        db = SessionLocal()
        try:
            config = db.query(CronConfig).filter(CronConfig.id == config_id).first()
            if not config:
                return {'status': 'error', 'message': '配置不存在'}
            
            if cron_expression is not None:
                config.cron_expression = cron_expression
            if enabled is not None:
                config.enabled = enabled
            if description is not None:
                config.description = description
            
            config.updated_at = datetime.now()
            db.commit()
            db.refresh(config)
            
            logger.info(f"更新cron配置: {config.task_name}")
            
            return {
                'status': 'success',
                'message': '配置已更新',
                'config': config.to_dict()
            }
            
        except Exception as e:
            db.rollback()
            logger.error(f"更新cron配置失败: {str(e)}")
            return {'status': 'error', 'message': str(e)}
        finally:
            db.close()


# 全局实例
cron_manager = CronManager()

